/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ChannelImport {
    order: bigint;
    name: string;
    description: string;
    isActive: boolean;
    logoUrl: string;
    category: string;
    streamUrl: string;
}
export interface SiteSettings {
    tagline: string;
    maintenanceMode: boolean;
    siteName: string;
    logoUrl: string;
    contactEmail: string;
    footerText: string;
}
export interface Channel {
    id: bigint;
    order: bigint;
    name: string;
    description: string;
    isActive: boolean;
    logoUrl: string;
    category: string;
    streamUrl: string;
}
export interface ApiSettings {
    enabled: boolean;
    apiToken: string;
}
export interface Account {
    id: bigint;
    username: string;
    password: string;
    role: string;
}
export interface Category {
    id: bigint;
    name: string;
    slug: string;
}
export interface backendInterface {
    addAccount(username: string, password: string, role: string, token: string): Promise<void>;
    addCategory(name: string, slug: string, token: string): Promise<void>;
    addChannel(channel: Channel, token: string): Promise<void>;
    adminLogin(username: string, password: string): Promise<string>;
    adminLogout(token: string): Promise<boolean>;
    deleteAccount(username: string, token: string): Promise<void>;
    deleteCategory(id: bigint, token: string): Promise<void>;
    deleteChannel(id: bigint, token: string): Promise<void>;
    getAccounts(token: string): Promise<Array<Account>>;
    getAccountsDebug(): Promise<Array<[string, Account]>>;
    getAllChannels(token: string): Promise<Array<Channel>>;
    getApiSettings(token: string): Promise<ApiSettings>;
    getCategories(): Promise<Array<Category>>;
    getCategoriesDebug(): Promise<Array<[string, Category]>>;
    getChannelById(id: bigint): Promise<Channel>;
    getChannels(): Promise<Array<Channel>>;
    getChannelsApi(apiToken: string): Promise<Array<Channel>>;
    getChannelsByCategory(categorySlug: string): Promise<Array<Channel>>;
    getChannelsDebug(): Promise<Array<[string, Channel]>>;
    getMyRole(token: string): Promise<string>;
    getSiteSettings(): Promise<SiteSettings>;
    importChannels(channelsToImport: Array<ChannelImport>, token: string): Promise<bigint>;
    updateAccount(username: string, password: string, role: string, token: string): Promise<void>;
    updateApiSettings(settings: ApiSettings, token: string): Promise<void>;
    updateCategory(category: Category, token: string): Promise<void>;
    updateChannel(channel: Channel, token: string): Promise<void>;
    updateSiteSettings(newSettings: SiteSettings, token: string): Promise<void>;
    validateSession(token: string): Promise<boolean>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAccount(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAccount(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAccount(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addCategory(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async addChannel(arg0: Channel, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addChannel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChannel(arg0, arg1);
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async adminLogout(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return result;
        }
    }
    async deleteAccount(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccount(arg0, arg1);
            return result;
        }
    }
    async deleteCategory(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0, arg1);
            return result;
        }
    }
    async deleteChannel(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChannel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChannel(arg0, arg1);
            return result;
        }
    }
    async getAccounts(arg0: string): Promise<Array<Account>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccounts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccounts(arg0);
            return result;
        }
    }
    async getAccountsDebug(): Promise<Array<[string, Account]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountsDebug();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountsDebug();
            return result;
        }
    }
    async getAllChannels(arg0: string): Promise<Array<Channel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChannels(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChannels(arg0);
            return result;
        }
    }
    async getApiSettings(arg0: string): Promise<ApiSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiSettings(arg0);
            return result;
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getCategoriesDebug(): Promise<Array<[string, Category]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoriesDebug();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoriesDebug();
            return result;
        }
    }
    async getChannelById(arg0: bigint): Promise<Channel> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelById(arg0);
            return result;
        }
    }
    async getChannels(): Promise<Array<Channel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannels();
            return result;
        }
    }
    async getChannelsApi(arg0: string): Promise<Array<Channel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelsApi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelsApi(arg0);
            return result;
        }
    }
    async getChannelsByCategory(arg0: string): Promise<Array<Channel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelsByCategory(arg0);
            return result;
        }
    }
    async getChannelsDebug(): Promise<Array<[string, Channel]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelsDebug();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelsDebug();
            return result;
        }
    }
    async getMyRole(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole(arg0);
            return result;
        }
    }
    async getSiteSettings(): Promise<SiteSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteSettings();
            return result;
        }
    }
    async importChannels(arg0: Array<ChannelImport>, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.importChannels(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importChannels(arg0, arg1);
            return result;
        }
    }
    async updateAccount(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAccount(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAccount(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateApiSettings(arg0: ApiSettings, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApiSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApiSettings(arg0, arg1);
            return result;
        }
    }
    async updateCategory(arg0: Category, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1);
            return result;
        }
    }
    async updateChannel(arg0: Channel, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChannel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChannel(arg0, arg1);
            return result;
        }
    }
    async updateSiteSettings(arg0: SiteSettings, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteSettings(arg0, arg1);
            return result;
        }
    }
    async validateSession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
